// Generated by Futhark 0.26.0 (prerelease - include info below when reporting bugs)
// git: ee56f96 (Thu Aug 3 12:16:33 2023 +0200) [modified]
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#define CL_TARGET_OPENCL_VERSION 120
#define CL_USE_DEPRECATED_OPENCL_1_2_APIS
#ifdef __APPLE__
#define CL_SILENCE_DEPRECATION
#include <OpenCL/cl.h>
#else
#include <CL/cl.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_add_build_option(struct futhark_context_config *cfg, const char *opt);
void futhark_context_config_set_device(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_set_platform(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_select_device_interactively(struct futhark_context_config *cfg);
void futhark_context_config_list_devices(struct futhark_context_config *cfg);
void futhark_context_config_dump_program_to(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_load_program_from(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_dump_binary_to(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_load_binary_from(struct futhark_context_config *cfg, const char *s);
void futhark_context_config_set_default_group_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_num_groups(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_tile_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_reg_tile_size(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_default_threshold(struct futhark_context_config *cfg, int size);
void futhark_context_config_set_command_queue(struct futhark_context_config *cfg, cl_command_queue);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_u32_2d;
struct futhark_u32_2d *futhark_new_u32_2d(struct futhark_context *ctx, const uint32_t *data, int64_t dim0, int64_t dim1);
struct futhark_u32_2d *futhark_new_raw_u32_2d(struct futhark_context *ctx, const cl_mem data, int64_t offset, int64_t dim0, int64_t dim1);
int futhark_free_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);
int futhark_values_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr, uint32_t *data);
cl_mem futhark_values_raw_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);
const int64_t *futhark_shape_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);
struct futhark_u8_1d;
struct futhark_u8_1d *futhark_new_u8_1d(struct futhark_context *ctx, const uint8_t *data, int64_t dim0);
struct futhark_u8_1d *futhark_new_raw_u8_1d(struct futhark_context *ctx, const cl_mem data, int64_t offset, int64_t dim0);
int futhark_free_u8_1d(struct futhark_context *ctx, struct futhark_u8_1d *arr);
int futhark_values_u8_1d(struct futhark_context *ctx, struct futhark_u8_1d *arr, uint8_t *data);
cl_mem futhark_values_raw_u8_1d(struct futhark_context *ctx, struct futhark_u8_1d *arr);
const int64_t *futhark_shape_u8_1d(struct futhark_context *ctx, struct futhark_u8_1d *arr);

// Opaque values
struct futhark_opaque_b2de7ac;
struct futhark_opaque_86dd06d3;
struct futhark_opaque_state;
struct futhark_opaque_40c80b6a;
struct futhark_opaque_721f284b;
struct futhark_opaque_84640977;
struct futhark_opaque_f5b98ad5;
struct futhark_opaque_9eab96ba;
struct futhark_opaque_11462a01;
int futhark_free_opaque_b2de7ac(struct futhark_context *ctx, struct futhark_opaque_b2de7ac *obj);
int futhark_store_opaque_b2de7ac(struct futhark_context *ctx, const struct futhark_opaque_b2de7ac *obj, void **p, size_t *n);
struct futhark_opaque_b2de7ac *futhark_restore_opaque_b2de7ac(struct futhark_context *ctx, const void *p);
int futhark_free_opaque_86dd06d3(struct futhark_context *ctx, struct futhark_opaque_86dd06d3 *obj);
int futhark_store_opaque_86dd06d3(struct futhark_context *ctx, const struct futhark_opaque_86dd06d3 *obj, void **p, size_t *n);
struct futhark_opaque_86dd06d3 *futhark_restore_opaque_86dd06d3(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_86dd06d3_0(struct futhark_context *ctx, uint64_t *out, const struct futhark_opaque_86dd06d3 *obj);
int futhark_project_opaque_86dd06d3_1(struct futhark_context *ctx, uint64_t *out, const struct futhark_opaque_86dd06d3 *obj);
int futhark_new_opaque_86dd06d3(struct futhark_context *ctx, struct futhark_opaque_86dd06d3 **out, const uint64_t v0, const uint64_t v1);
int futhark_free_opaque_state(struct futhark_context *ctx, struct futhark_opaque_state *obj);
int futhark_store_opaque_state(struct futhark_context *ctx, const struct futhark_opaque_state *obj, void **p, size_t *n);
struct futhark_opaque_state *futhark_restore_opaque_state(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_state_auto_zoom(struct futhark_context *ctx, struct futhark_opaque_f5b98ad5 **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_base(struct futhark_context *ctx, struct futhark_opaque_40c80b6a **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_height(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_mouse(struct futhark_context *ctx, struct futhark_opaque_11462a01 **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_screen_calculations(struct futhark_context *ctx, struct futhark_opaque_84640977 **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_viewport(struct futhark_context *ctx, struct futhark_opaque_721f284b **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_width(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_state *obj);
int futhark_new_opaque_state(struct futhark_context *ctx, struct futhark_opaque_state **out, const struct futhark_opaque_f5b98ad5 *f_auto_zzoom, const struct futhark_opaque_40c80b6a *f_base, const int64_t f_height, const struct futhark_opaque_11462a01 *f_mouse, const struct futhark_opaque_84640977 *f_screen_calculations, const struct futhark_opaque_721f284b *f_viewport, const int64_t f_width);
int futhark_free_opaque_40c80b6a(struct futhark_context *ctx, struct futhark_opaque_40c80b6a *obj);
int futhark_store_opaque_40c80b6a(struct futhark_context *ctx, const struct futhark_opaque_40c80b6a *obj, void **p, size_t *n);
struct futhark_opaque_40c80b6a *futhark_restore_opaque_40c80b6a(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_40c80b6a_approach(struct futhark_context *ctx, struct futhark_opaque_b2de7ac **out, const struct futhark_opaque_40c80b6a *obj);
int futhark_project_opaque_40c80b6a_rng(struct futhark_context *ctx, struct futhark_opaque_86dd06d3 **out, const struct futhark_opaque_40c80b6a *obj);
int futhark_project_opaque_40c80b6a_time(struct futhark_context *ctx, float *out, const struct futhark_opaque_40c80b6a *obj);
int futhark_new_opaque_40c80b6a(struct futhark_context *ctx, struct futhark_opaque_40c80b6a **out, const struct futhark_opaque_b2de7ac *f_approach, const struct futhark_opaque_86dd06d3 *f_rng, const float f_time);
int futhark_free_opaque_721f284b(struct futhark_context *ctx, struct futhark_opaque_721f284b *obj);
int futhark_store_opaque_721f284b(struct futhark_context *ctx, const struct futhark_opaque_721f284b *obj, void **p, size_t *n);
struct futhark_opaque_721f284b *futhark_restore_opaque_721f284b(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_721f284b_center(struct futhark_context *ctx, struct futhark_opaque_9eab96ba **out, const struct futhark_opaque_721f284b *obj);
int futhark_project_opaque_721f284b_zoom(struct futhark_context *ctx, float *out, const struct futhark_opaque_721f284b *obj);
int futhark_new_opaque_721f284b(struct futhark_context *ctx, struct futhark_opaque_721f284b **out, const struct futhark_opaque_9eab96ba *f_center, const float f_zzoom);
int futhark_free_opaque_84640977(struct futhark_context *ctx, struct futhark_opaque_84640977 *obj);
int futhark_store_opaque_84640977(struct futhark_context *ctx, const struct futhark_opaque_84640977 *obj, void **p, size_t *n);
struct futhark_opaque_84640977 *futhark_restore_opaque_84640977(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_84640977_center_offset(struct futhark_context *ctx, struct futhark_opaque_9eab96ba **out, const struct futhark_opaque_84640977 *obj);
int futhark_project_opaque_84640977_offset_viewport_scaled(struct futhark_context *ctx, struct futhark_opaque_9eab96ba **out, const struct futhark_opaque_84640977 *obj);
int futhark_project_opaque_84640977_precision(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_84640977 *obj);
int futhark_project_opaque_84640977_xy_factor_inv(struct futhark_context *ctx, float *out, const struct futhark_opaque_84640977 *obj);
int futhark_project_opaque_84640977_zoom_factor(struct futhark_context *ctx, float *out, const struct futhark_opaque_84640977 *obj);
int futhark_new_opaque_84640977(struct futhark_context *ctx, struct futhark_opaque_84640977 **out, const struct futhark_opaque_9eab96ba *f_center_offset, const struct futhark_opaque_9eab96ba *f_offset_viewport_scaled, const int64_t f_precision, const float f_xy_factor_inv, const float f_zzoom_factor);
int futhark_free_opaque_f5b98ad5(struct futhark_context *ctx, struct futhark_opaque_f5b98ad5 *obj);
int futhark_store_opaque_f5b98ad5(struct futhark_context *ctx, const struct futhark_opaque_f5b98ad5 *obj, void **p, size_t *n);
struct futhark_opaque_f5b98ad5 *futhark_restore_opaque_f5b98ad5(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_f5b98ad5_enabled(struct futhark_context *ctx, bool *out, const struct futhark_opaque_f5b98ad5 *obj);
int futhark_project_opaque_f5b98ad5_factor(struct futhark_context *ctx, float *out, const struct futhark_opaque_f5b98ad5 *obj);
int futhark_new_opaque_f5b98ad5(struct futhark_context *ctx, struct futhark_opaque_f5b98ad5 **out, const bool f_enabled, const float f_factor);
int futhark_free_opaque_9eab96ba(struct futhark_context *ctx, struct futhark_opaque_9eab96ba *obj);
int futhark_store_opaque_9eab96ba(struct futhark_context *ctx, const struct futhark_opaque_9eab96ba *obj, void **p, size_t *n);
struct futhark_opaque_9eab96ba *futhark_restore_opaque_9eab96ba(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_9eab96ba_x(struct futhark_context *ctx, float *out, const struct futhark_opaque_9eab96ba *obj);
int futhark_project_opaque_9eab96ba_y(struct futhark_context *ctx, float *out, const struct futhark_opaque_9eab96ba *obj);
int futhark_new_opaque_9eab96ba(struct futhark_context *ctx, struct futhark_opaque_9eab96ba **out, const float f_x, const float f_y);
int futhark_free_opaque_11462a01(struct futhark_context *ctx, struct futhark_opaque_11462a01 *obj);
int futhark_store_opaque_11462a01(struct futhark_context *ctx, const struct futhark_opaque_11462a01 *obj, void **p, size_t *n);
struct futhark_opaque_11462a01 *futhark_restore_opaque_11462a01(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_11462a01_x(struct futhark_context *ctx, int32_t *out, const struct futhark_opaque_11462a01 *obj);
int futhark_project_opaque_11462a01_y(struct futhark_context *ctx, int32_t *out, const struct futhark_opaque_11462a01 *obj);
int futhark_new_opaque_11462a01(struct futhark_context *ctx, struct futhark_opaque_11462a01 **out, const int32_t f_x, const int32_t f_y);

// Entry points
int futhark_entry_grab_mouse(struct futhark_context *ctx, bool *out0);
int futhark_entry_init(struct futhark_context *ctx, struct futhark_opaque_state **out0, const uint32_t in0, const int32_t in1, const int32_t in2);
int futhark_entry_key(struct futhark_context *ctx, struct futhark_opaque_state **out0, const int32_t in0, const int32_t in1, const struct futhark_opaque_state *in2);
int futhark_entry_mouse(struct futhark_context *ctx, struct futhark_opaque_state **out0, const int32_t in0, const int32_t in1, const int32_t in2, const struct futhark_opaque_state *in3);
int futhark_entry_render(struct futhark_context *ctx, struct futhark_u32_2d **out0, const struct futhark_opaque_state *in0);
int futhark_entry_resize(struct futhark_context *ctx, struct futhark_opaque_state **out0, const int32_t in0, const int32_t in1, const struct futhark_opaque_state *in2);
int futhark_entry_step(struct futhark_context *ctx, struct futhark_opaque_state **out0, const float in0, const struct futhark_opaque_state *in1);
int futhark_entry_text_colour(struct futhark_context *ctx, uint32_t *out0, const struct futhark_opaque_state *in0);
int futhark_entry_text_content(struct futhark_context *ctx, int32_t *out0, int32_t *out1, float *out2, float *out3, float *out4, int32_t *out5, const float in0, const struct futhark_opaque_state *in1);
int futhark_entry_text_format(struct futhark_context *ctx, struct futhark_u8_1d **out0);
int futhark_entry_wheel(struct futhark_context *ctx, struct futhark_opaque_state **out0, const int32_t in0, const int32_t in1, const struct futhark_opaque_state *in2);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
cl_command_queue futhark_context_get_command_queue(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_report(struct futhark_context *ctx);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_opencl
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
